version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://circleci_test_user:circle@localhost/circle_test

      - image: circleci/postgres:12.3 # should match Heroku Postgres
        environment:
          POSTGRES_USERNAME: circleci_test_user
          POSTGRES_PASSWORD: circle

      - image: circleci/redis:4.0.14-alpine # should match Heroku Redis version

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update && sudo apt install postgresql-client

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run migrations
          command: pipenv run flask db upgrade

      - run:
          name: run tests
          command: pipenv run test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
