version: 2.1

jobs:
  build-and-test-python:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://test:rr@localhost/redditraffler_test

      - image: postgres:12.3-alpine # should match Heroku Postgres version
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: rr
          POSTGRES_DB: redditraffler_test

      - image: circleci/redis:4.0.14-alpine # should match Heroku Redis version

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update && sudo apt install postgresql-client

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run migrations
          command: pipenv run flask db upgrade

      - run:
          name: run tests and report coverage
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            pipenv run coverage run -m pytest -vv tests
            pipenv run coverage xml
            ./cc-test-reporter after-build

  build-and-test-js:
    docker:
      - image: cimg/node:12.18

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: yarn install --dev

      - run:
          name: run tests
          command: yarn test
        
workflows:
  version: 2
  build-and-test-python:
    jobs:
      - build-and-test-python

  build-and-test-js:
    jobs:
      - build-and-test-js
