version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test

      - image: circleci/postgres:9.6.5-alpine-ram
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt update && sudo apt install postgresql-client

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: run migrations
          command: pipenv run flask db upgrade

      - run:
          name: run tests
          command: pipenv run test

      - store_artifacts:
          path: test-reports
          destination: test-reports
