# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.5-alpine-ram
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo sed -i '/jessie-updates/d' /etc/apt/sources.list # https://github.com/debuerreotype/docker-debian-artifacts/issues/66
      - run: sudo apt update
      - run: sudo apt install postgresql-client

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: pipenv install

      - run:
          name: run migrations
          command: pipenv run flask db upgrade
            . venv/bin/activate
            flask db upgrade

      - run:
          name: run tests
          command: pipenv run pytest --verbose

      - store_artifacts:
          path: test-reports
          destination: test-reports
