"""Add Winner table

Revision ID: 199871761a3f
Revises: 7b2fb7dfbdb2
Create Date: 2018-02-22 15:14:28.794809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199871761a3f'
down_revision = '7b2fb7dfbdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('account_age', sa.Integer(), nullable=True),
    sa.Column('comment_karma', sa.Integer(), nullable=True),
    sa.Column('link_karma', sa.Integer(), nullable=True),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winner_raffle_id'), 'winner', ['raffle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winner_raffle_id'), table_name='winner')
    op.drop_table('winner')
    # ### end Alembic commands ###
