"""Add refresh token column to users

Revision ID: 21befca33886
Revises: 275d2acb0afa
Create Date: 2019-07-29 19:19:17.689959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21befca33886"
down_revision = "275d2acb0afa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("refresh_token_enc", sa.LargeBinary(), nullable=True, unique=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "refresh_token_enc")
    # ### end Alembic commands ###
