"""Explicit null validation on columns

Revision ID: 275d2acb0afa
Revises: 1e13ad86bf0d
Create Date: 2019-05-04 11:26:24.691581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275d2acb0afa'
down_revision = '1e13ad86bf0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffle', sa.Column('min_combined_karma', sa.Integer(), nullable=True))
    op.alter_column('raffle', 'min_account_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('raffle', 'submission_author',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('raffle', 'submission_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('raffle', 'submission_title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('raffle', 'subreddit',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('raffle', 'winner_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('winner', 'account_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('winner', 'comment_karma',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('winner', 'comment_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('winner', 'link_karma',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('winner', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('winner', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('winner', 'link_karma',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('winner', 'comment_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('winner', 'comment_karma',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('winner', 'account_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('raffle', 'winner_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('raffle', 'subreddit',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('raffle', 'submission_title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('raffle', 'submission_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('raffle', 'submission_author',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('raffle', 'min_account_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('raffle', 'min_combined_karma')
    # ### end Alembic commands ###
