"""Add index to Raffle.user_id

Revision ID: 7b2fb7dfbdb2
Revises: b4747c680cda
Create Date: 2018-02-22 14:43:14.692694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2fb7dfbdb2'
down_revision = 'b4747c680cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_raffle_user_id'), 'raffle', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raffle_user_id'), table_name='raffle')
    # ### end Alembic commands ###
