"""Add Raffle table

Revision ID: b4747c680cda
Revises: fd57c645e4e5
Create Date: 2018-02-22 14:40:35.561433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4747c680cda'
down_revision = 'fd57c645e4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raffle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submission_id', sa.String(length=64), nullable=True),
    sa.Column('submission_title', sa.String(length=128), nullable=True),
    sa.Column('submission_author', sa.String(length=64), nullable=True),
    sa.Column('winner_count', sa.Integer(), nullable=True),
    sa.Column('minimum_account_age', sa.Integer(), nullable=True),
    sa.Column('minimum_ckarma', sa.Integer(), nullable=True),
    sa.Column('minimum_lkarma', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_submission_id'), 'raffle', ['submission_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raffle_submission_id'), table_name='raffle')
    op.drop_table('raffle')
    # ### end Alembic commands ###
