"""Add comment url column to Winner model

Revision ID: fa954b7c2e86
Revises: 199871761a3f
Create Date: 2018-02-28 09:18:32.390984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa954b7c2e86'
down_revision = '199871761a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winner', sa.Column('comment_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winner', 'comment_url')
    # ### end Alembic commands ###
